import "server-only";

import {
  ListingCondition,
  ListingStatus,
  Marketplace,
  Prisma,
  SellingGoal,
} from "@prisma/client";

import { prisma } from "@/lib/db";

export interface ListingOutput {
  optimized_title: string;
  mobile_title: string;
  category_suggestion: string;
  item_specifics: Record<string, string>;
  condition_description: string;
  seo_description: string;
  pricing: {
    low: number;
    target: number;
    high: number;
    rationale: string;
  };
  shipping: {
    weight: string;
    packaging: string;
    carrier: string;
    paid_by: string;
  };
  keywords: string[];
  photo_notes: string[];
  cross_listing_short: string;
  confidence: "low" | "med" | "high";
  uncertainty_flags: string[];
}

/**
 * Returns a plausibly-shaped canned output object.
 * Real LLM-generated content will replace this in W3.
 */
export function cannedListingOutput(): ListingOutput {
  return {
    optimized_title: "Listing draft — content will be generated by AI in W3",
    mobile_title: "Draft listing — AI title coming in W3",
    category_suggestion: "To be determined by AI analysis",
    item_specifics: {
      Brand: "To be filled by AI",
      Model: "To be filled by AI",
      Condition: "To be filled by AI",
    },
    condition_description:
      "Condition details will be generated based on your photos and defect notes in W3.",
    seo_description:
      "A full SEO-optimized description highlighting key features, condition, and value will be generated by AI in W3. This placeholder will be replaced with compelling buyer-focused copy.",
    pricing: {
      low: 0,
      target: 0,
      high: 0,
      rationale:
        "Pricing analysis based on recent sold comps will be provided by AI in W3.",
    },
    shipping: {
      weight: "TBD",
      packaging: "TBD",
      carrier: "TBD",
      paid_by: "seller",
    },
    keywords: ["draft", "placeholder", "ai-generated-in-w3"],
    photo_notes: [],
    cross_listing_short:
      "Short cross-listing description will be generated by AI in W3.",
    confidence: "low",
    uncertainty_flags: [
      "This is a placeholder output — real analysis requires W3 LLM integration.",
    ],
  };
}

export interface CreateListingParams {
  userId: string;
  marketplace: Marketplace;
  photos: string[];
  productName?: string;
  brand?: string;
  model?: string;
  accessories?: string;
  defects?: string;
  condition?: ListingCondition;
  sellingGoal?: SellingGoal;
  output: ListingOutput;
}

/**
 * Persists a new Listing row for the given user and returns it.
 * Status is always DRAFT on creation.
 */
export async function createListingForUser(params: CreateListingParams) {
  const {
    userId,
    marketplace,
    photos,
    productName,
    brand,
    model,
    accessories,
    defects,
    condition,
    sellingGoal,
    output,
  } = params;

  return prisma.listing.create({
    data: {
      userId,
      marketplace,
      photos,
      productName: productName ?? null,
      brand: brand ?? null,
      model: model ?? null,
      accessories: accessories ?? null,
      defects: defects ?? null,
      condition: condition ?? null,
      sellingGoal: sellingGoal ?? null,
      // ListingOutput is a typed interface without an index signature;
      // Prisma's Json column wants InputJsonValue. Safe cast — the runtime
      // shape is plain JSON-compatible.
      output: output as unknown as Prisma.InputJsonValue,
      status: ListingStatus.DRAFT,
    },
  });
}
